### ISSUE TITLE
make an XSLT 3 version

### ISSUE THREAD

**Issue by stegarcia** [dtardon/xslt2-transformer#3]
Hello,

I would like to add an XML filter in Libre Office based on XSL 3.0 but it is not working. The closest development I found is this extension. Though it is meant for XSL 2.0. Would it be possible to make it compliant with XSL 3.0?

**Comment by stegarcia** [comment]
would replacing saxon9.jar in external by saxon HE10 work?

**Comment by dtardon** [comment]
This project is really just an archive of code that used to be a part of LibreOffice. It was removed (mainly because it relied on an old and unsupported version of Saxon), but we (I was a LibreOffice developer then) felt it should be kept available for those who do have any XSLT 2.0 filter. Therefore, I turned it into an extension. But it was a one-time action; I've never expected to do any further development. Sorry if that's disappointing.
